// Code generated by sqlc. DO NOT EDIT.
// source: person.sql

package db

import (
	"context"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO person (
    name, age
) VALUES (
             $1, $2
         )
    RETURNING id, name, age
`

type CreatePersonParams struct {
	Name string `json:"name"`
	Age  string `json:"age"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson, arg.Name, arg.Age)
	var i Person
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}
